# Generated by Django 6.0.2 on 2026-04-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
