# Generated by Django 6.0.2 on 2026-04-23 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_student_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
    ]
