# Generated by Django 6.0.2 on 2026-04-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_student_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
