# Generated by Django 6.0.2 on 2026-04-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
